In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4,5])*2
print(a)

[ 2  4  6  8 10]


In [ ]:
a=[1,2,3,4,5]*2
print(a)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
import time
a=[1,2,3,4,5]*10000
start=time.time()
for i in range(len(a)):
  a[i]=a[i]*2
print("\n time taken for list:",time.time()-start)


 time taken for list: 0.00753331184387207


In [ ]:
a=[1,2,3,4,5]*10000
b=np.array(a)
start=time.time()
new_b=b*2
print("\n time taken for list:",time.time()-start)


 time taken for list: 0.0005223751068115234


In [ ]:
import sys
a=[1,2,3,4,5]
arr=np.array(a)

print("list size:",  sys.getsizeof(a))
print("array size:", arr.nbytes)

list size: 104
array size: 40


In [ ]:
a=[1,'a','raj',2.0]
print(type(a))

<class 'list'>


all data types converted into a string in numpy

In [ ]:
arr=np.array(a)
arr

array(['1', 'a', 'raj', '2.0'], dtype='<U32')

one dimentional array

In [ ]:
a=np.array([])
a.ndim
a.shape

(0,)

two dimentional array

In [ ]:
a=np.array([[]])
a.ndim
a.shape

(1, 0)

three dimentional array

In [ ]:
a=np.array([[[]]])
a.ndim
a.shape

(1, 1, 0)

In [ ]:
range=np.arange(1,10)  #start,stop
range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
range=np.arange(1,10,2)  #start,stop,step
range

array([1, 3, 5, 7, 9])

In [ ]:
arr=np.linspace(0,1,5)  # start,stop,no.of values
arr


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
arr=np.logspace(1,3,3)  #(start,stop,scale no.of values)logarithmic scale array--10^1--10^2--10^3
arr

array([  10.,  100., 1000.])

In [ ]:
arr=np.zeros(5) # array full of zeros
arr

array([0., 0., 0., 0., 0.])

In [ ]:
arr=np.zeros([2,3])  # 2rows,3columns of zeros
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr=np.ones([2,3])  # 2rows,3columns array ful of ones
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr=np.full([2,4],7) # [2rows,4columns],default values is 7
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
arr=np.empty([2,3])  # create any array without setting any values
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr=np.random.rand(10)  # random float (0,1)
arr

array([0.94583108, 0.08659971, 0.70039211, 0.52781452, 0.67047917,
       0.90967256, 0.77938643, 0.20927445, 0.933912  , 0.59850336])

In [ ]:
arr=np.random.randn(2,3)  # random float from standard normal distribution
arr

array([[0.2352029 , 2.02274565, 0.66578205],
       [0.51878552, 0.44813071, 0.73697556]])

In [ ]:
arr=np.random.randint(10,100) # start,stop,dimention/
arr

28

In [ ]:
arr=np.random.randint(10,100,size=(2,3))  # ranint create 2rows,3columns,between 10 to 100
arr

array([[44, 43, 81],
       [70, 56, 53]])

In [ ]:
arr=np.array([1,2,3.1,4,5])
arr

array([1. , 2. , 3.1, 4. , 5. ])

In [ ]:
arr.dtype # numpy automaticaly convert defaulat float64 depend on values

dtype('float64')

In [ ]:
arr=np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [ ]:
arr=np.array([1,2,3,4],dtype=np.float32)  #convert datatype int to float
arr.dtype
arr

array([1., 2., 3., 4.], dtype=float32)

Type casting **error**

In [ ]:
arr=np.arry(["1","2","rajesh"])  #multiple charecter(string) we can not convert int or float
arr1=arr.astype(np.int64)
arr1

AttributeError: module 'numpy' has no attribute 'arry'

In [ ]:
arr=np.array([[1,2,3],
             [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.size

6

In [ ]:
arr.itemsize

8

**Array reshaping**

In [ ]:
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
reshaped1=reshaped.reshape(3,2)
reshaped1

array([[1, 2],
       [3, 4],
       [5, 6]])

**Ravel**

In [ ]:
ravel1=reshaped1.ravel()  #ravel converted into one d array
ravel1

array([1, 2, 3, 4, 5, 6])