In [ ]:
import numpy as np

Arithmaetic operations on array


In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [ ]:
print(a+b)

[ 6  8 10 12]


In [ ]:
print(a-b)

[-4 -4 -4 -4]


In [ ]:
print(a*b)

[ 5 12 21 32]


In [ ]:
print(a/b)

[0.2        0.33333333 0.42857143 0.5       ]


In [ ]:
print(b/a)

[5.         3.         2.33333333 2.        ]


In [ ]:
print(b//a) # it shows integer devision

[5 3 2 2]


In [ ]:
print(b%a) # remainder

[0 0 1 0]


In [ ]:
print(a**b) # power

[    1    64  2187 65536]


Universal functions

In [ ]:
arr=np.array([1,4,9,16])

In [ ]:
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [ ]:
print(np.exp([1,2]))  #exponentioal -->np.exp -->e^x -> x is any integer

[2.71828183 7.3890561 ]


s**ine function --> np.sin** **bold text**

In [ ]:
angles=np.array([0,np.pi/2,np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


**indexing and slicing**

In [ ]:
a=[1,2,3,4,5]

In [ ]:
a[-1:-4]

array([], dtype=int64)

In [ ]:
a[-1:-4: -1]

array([4, 3, 2])

In [ ]:
a[ : :2]

array([1, 3])

In [ ]:
arr=np.array([10,20,30,40,50])  # array indexing

In [ ]:
print(arr[0])

10


In [ ]:
print(arr[-1])

50


In [ ]:
print(arr[1:4]) # slicing array [start:stop:step]

[20 30 40]


In [ ]:
print(arr[:3]) # first three elements

[10 20 30]


In [ ]:
print(arr[2:])  #from index 2 to end

[30 40 50]


In [ ]:
print(arr[::2])  #every secound element

[10 30 50]


In [ ]:
print(arr[::-1]) # reverse array

[50 40 30 20 10]


In [ ]:
import numpy as np  # 2D array indexing

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(arr[1,2])

6


In [ ]:
print(arr[0:2,:]) # access first two rows

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr[1:, 1:])

[[5 6]
 [8 9]]


np.take() is used to extract elements from an array using specified indices

In [ ]:
arr=np.array([10,20,30,40,50])
result=np.take(arr,[0,2,4])
print(result)

[10 30 50]


In [ ]:
arr = np.array([10, 20, 30, 40])  # repeated indices
result = np.take(arr, [1, 1, 3])
print(result)

[20 20 40]


In [ ]:
arr = np.array([[1, 2],    # 2D array
                [3, 4]])
result = np.take(arr, [0, 3])
print(result)

[1 4]


In [ ]:
arr = np.array([[10, 20, 30],  # using axis, axis=1 means columns, takes column 0 and column 2
                [40, 50, 60]])
result = np.take(arr, [0, 2], axis=1)
print(result)

[[10 30]
 [40 60]]


In [ ]:
arr = np.array([10, 20, 30])  # nditer( only values) 1D array
for x in np.nditer(arr):
    print(x)

10
20
30


In [ ]:
arr=np.array([[1,2],    # nditer 2D array
              [3,4]])
for x in np.nditer(arr):
  print(x, end=" ")

1 2 3 4 

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6


In [ ]:
arr = np.array([       # nditer 3D array
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

for x in np.nditer(arr):
    print(x , end=" ")

1 2 3 4 5 6 7 8 

In [ ]:
for index, value in np.ndenumerate(arr):   # ndenumerate both index + values
  print(index, value)

(0,) 10
(1,) 20
(2,) 30


In [ ]:
arr = np.array([10, 20, 30])   # ndenumerate 1D array
for index, value in np.ndenumerate(arr):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30


In [ ]:
arr=np.array([[10,20],    # ndenumerate 2D array
             [30,40]])
for index,value in np.ndenumerate(arr):
  print(index,value)

(0, 0) 10
(0, 1) 20
(1, 0) 30
(1, 1) 40


**views and copies**

In [ ]:
arr=np.array([10,20,30,40,50])
view=arr[1:3]
view

array([20, 30])

In [ ]:
arr[0]=100

In [ ]:
arr

array([100,  20,  30,  40,  50])

In [ ]:
view[0]=200

In [ ]:
view

array([200,  30])

In [ ]:
arr

array([100, 200,  30,  40,  50])

In [ ]:
copy=arr[1:3].copy()  # copy create completely separate array with its own memmory
copy

array([200,  30])

In [ ]:
copy[0]=2
copy

array([ 2, 30])

In [ ]:
arr  # changing copy does not effect arr

array([100, 200,  30,  40,  50])

transpose() or T,  swap rows and columns



In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr=np.array([[1,2],[3,4]])
print(arr.T)

[[1 3]
 [2 4]]


swapaxes --> swap two axes   np.swapaxes(array,axis1,axis2)
array___>input array,
axis1____>first axis,
axis2___>secound axis

In [ ]:
arr=np.array([[1,2,3],
              [4,5,6]])
result=np.swapaxes(arr,0,1)
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
result.shape  # 3rows, 2columns

(3, 2)

In [ ]:
arr.shape    #2rows, 3columns

(2, 3)

In [ ]:
arr=np.array([[[1,2],[3,4]]])   # 1 array,2 rows,2 columns
arr.shape

(1, 2, 2)

In [ ]:
swap=np.swapaxes(arr,0,1)  # 0 and 1 positions are swap
swap.shape

(2, 1, 2)

In [ ]:
arr.shape

(1, 2, 2)

concatination


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
combine=np.concatenate((a,b))
print(combine)

[1 2 3 4 5 6]


In [ ]:
arr1=np.array([[1,2],[3,4]])  # vstack vertical stack means vertical line
arr2=np.array([[5,6],[7,8]])
print(np.vstack((arr1,arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
arr1=np.array([[1,2],[3,4]])  # hstack means horizontall line
arr2=np.array([[5,6],[7,8]])
print(np.hstack((arr1,arr2)))

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(np.concatenate((arr1,arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
print(np.stack((arr1,arr2),axis=0)) # axis=0 means rows wise

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
print(np.stack((arr1,arr2),axis=1)) # axis=1 means columns wise

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [ ]:
print(np.split(arr1,2))  # here 2 means no.of split

[array([[1, 2]]), array([[3, 4]])]


In [ ]:
print(np.hsplit(arr1,2))


[array([[1],
       [3]]), array([[2],
       [4]])]


In [ ]:
print(np.vsplit(arr1,2))


[array([[1, 2]]), array([[3, 4]])]


Repeating

In [ ]:
arr=np.array([1,2,3])
print(np.repeat(arr,2))

[1 1 2 2 3 3]


In [ ]:
print(np.repeat(arr,3))


[1 1 1 2 2 2 3 3 3]


tille(repeat my whole array )

In [ ]:
print(np.tile(arr,2))

[1 2 3 1 2 3]


In [ ]:
print(np.tile(arr,3))


[1 2 3 1 2 3 1 2 3]


aggregation element

In [ ]:
arr=np.array([1,2,3])
print(np.sum(arr))

6


In [ ]:
np.mean(arr)

np.float64(2.0)

In [ ]:
np.median(arr)

np.float64(2.0)

In [ ]:
np.std(arr)

np.float64(0.816496580927726)

In [ ]:
np.var(arr)

np.float64(0.6666666666666666)

In [ ]:
np.min(arr)

np.int64(1)

In [ ]:
matrix=np.array([[1,2,3],
       [4,5,6],
       [7,8,9]])
print(np.sum(matrix,axis=1))

[ 6 15 24]


cumulative operations(running total)

In [ ]:
arr=np.array([1,2,3])   # 1, 1+2=3, 3+3=6
print(np.cumsum(arr))

[1 3 6]


In [ ]:
arr=np.array([1,2,3,4])  # 1 , 1*2=2, 2*3=6, 6*4=24
print(np.cumprod(arr))

[ 1  2  6 24]


where

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
result=np.where(arr<2, "low","high")

In [ ]:
result

array(['low', 'high', 'high', 'high'], dtype='<U4')

In [ ]:
arr=np.array([10,20,30,40])
print(np.argwhere(arr>20))

[[2]
 [3]]


In [ ]:
arr1=np.logical_and(arr>10, arr<40)
arr1

array([False,  True,  True, False])

In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(np.argwhere(matrix > 5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


logical and

In [ ]:
arr=np.array([10,20,30,40,50,60,70])
mask=np.logical_and(arr > 10, arr < 50)
mask

array([False,  True,  True,  True, False, False, False])

In [ ]:
arr[mask]

array([20, 30, 40])

logical or

In [ ]:
mask=np.logical_or(arr < 10 , arr > 50)
mask

array([False, False, False, False, False,  True,  True])

In [ ]:
arr[mask]

array([60, 70])

broadcasting(scaller + array)

In [ ]:
arr=np.array([1,2,3,4])
print(arr + 10)

[11 12 13 14]


In [ ]:
a=np.array([1,2,3,4])      # two arrays
b=np.array([10,20,30,40])
print(a+b)

[11 22 33 44]


In [ ]:
a=np.array([[1,2,3,4],
            [5,6,7,8]])      # 2D array + 1D array
b=np.array([10,20,30,40])
print(a+b)

[[11 22 33 44]
 [15 26 37 48]]


In [ ]:
image=np.array([[200,150],
                [100,250]])
image.shape

(2, 2)

In [ ]:
brightness=image + 50
brightness

array([[250, 200],
       [150, 300]])

vectorization(convert a regular function to be applied on an array)

In [ ]:
def square(x):
  return x*x
vfunc=np.vectorize(square)


In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
print(vfunc(arr))

[ 1  4  9 16]


np.isnan()--->( not a number)

In [ ]:
arr=np.array([1,np.nan,3,np.nan])  # true---> value is NaN
print(np.isnan(arr))

[False  True False  True]


np.isinf()--->value is positive infinity(inf) or negative infinity(-inf)

In [ ]:
arr=np.array([1,np.inf,-np.inf,5])
print(np.isinf(arr))

[False  True  True False]


np.isinfinite()--->values finite numbers(fiite means  not NaN and not infinity)

In [ ]:
arr=np.array([1,np.nan,np.inf,10])
print(np.isfinite(arr))

[ True False False  True]
